FROM rocker/verse:4.3.1
RUN apt-get update -y && apt-get install -y  make libgmp3-dev libmpfr-dev libcairo2-dev zlib1g-dev pandoc libx11-dev libcurl4-openssl-dev libssl-dev perl libicu-dev libgsl0-dev libxml2-dev cmake libjpeg-dev libpng-dev libfontconfig1-dev libfreetype6-dev libglpk-dev libtiff-dev libfribidi-dev libharfbuzz-dev git python3 && rm -rf /var/lib/apt/lists/*
RUN apt-get update -y && apt-get install -y libmagick++-dev
RUN apt-get install -y gsfonts && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /usr/local/lib/R/etc/ /usr/lib/R/etc/
RUN echo "options(renv.config.pak.enabled = FALSE, repos = c(CRAN = 'https://cran.rstudio.com/'), download.file.method = 'libcurl', Ncpus = 4)" | tee /usr/local/lib/R/etc/Rprofile.site | tee /usr/lib/R/etc/Rprofile.site
RUN R -e 'install.packages("remotes")'
RUN R -e 'remotes::install_version("renv", version = "1.0.3")'
COPY renv.lock.prod renv.lock
RUN R -e 'renv::restore()'
